version: '0.0.{build}'

image: Visual Studio 2017

init:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

configuration:
  - Debug
  - Release

environment:
  matrix:
  - arch: x86
    platform: Win32
    visual_studio: Visual Studio 15 2017
    gtest: 1.7.0
    OpenSSL: 1.0.2n

  - arch: x86_64
    platform: x64
    visual_studio: Visual Studio 15 2017 Win64
    gtest: 1.8.1
    OpenSSL: 1.0.2n

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

build_script:
  - md build
  - cd build
  - conan install .. -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -o gtest=%GTEST% -o OpenSSL=%OPENSSL%
  - cmake .. -G "%VISUAL_STUDIO%"
  - msbuild JSONSettings.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - conan export-pkg ../conanfile.py JSONSettings/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -o gtest=%GTEST% -o OpenSSL=%OPENSSL%
  - conan test ../test_package/conanfile.py JSONSettings/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -o gtest=%GTEST% -o OpenSSL=%OPENSSL%
  - cd ..
  - cd test
  - cd JSONSettingsTestUtilities
  - md build
  - cd build
  - conan install .. -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -e VERSION="%APPVEYOR_BUILD_VERSION%" -o gtest=%GTEST% -o OpenSSL=%OPENSSL%
  - cmake .. -G "%VISUAL_STUDIO%"
  - msbuild JSONSettingsTestUtilities.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - conan export-pkg ../conanfile.py JSONSettingsTestUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -o gtest=%GTEST% -o OpenSSL=%OPENSSL%
  - conan test ../test_package/conanfile.py JSONSettingsTestUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -o gtest=%GTEST% -o OpenSSL=%OPENSSL%
  - cd ..
  - cd ..
  - cd ..
  - cd build

test_script:
  - ps: cd bin
  - ps: cd $env:CONFIGURATION
  - JSONSettingsTest.exe --gtest_output=xml:JSONSettingsTest.xml

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\JSONSettingsTest.xml))

artifacts:
  - path: 'build\lib\%CONFIGURATION%\JSONSettings.lib'
    name: JSONSettings.lib
  - path: 'test\JSONSettingsTestUtilities\build\lib\%CONFIGURATION%\JSONSettingsTestUtilities.lib'
    name: JSONSettingsTestUtilities.lib

deploy_script:
  - ps: >- 
      if($env:appveyor_repo_tag -eq 'True') {
        conan upload JSONSettings/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
        conan upload JSONSettingsTestUtilities/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
      } else {
        echo "Not uploading because this is not a tag build"
      }
