version: '0.0.{build}'

init:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

configuration:
  - Debug
  - Release

environment:
  global:
    PYTHON: "C:\\Python36"

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    arch: x86_64
    platform: x64
    visual_studio: Visual Studio 16 2019
    compiler_toolset: v142
    gtest: 1.10.0
    openssl: 1.1.1g
    boost: 1.71.0

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: x86
    platform: Win32
    visual_studio: Visual Studio 15 2017
    compiler_toolset: v141
    boost: 1.66.0
    openssl: 1.1.1g
    gtest: 1.7.0

install:
  - "SET PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%"
  - pip.exe install conan
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

build_script:
  - md build
  - cd build
  - conan install .. -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o boost=%BOOST% -o gtest=%GTEST%
  - cmake .. -G "%VISUAL_STUDIO%" -A %PLATFORM%
  - msbuild JSONSettings.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - conan export-pkg ../conanfile.py JSONSettings/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o boost=%BOOST% -o gtest=%GTEST%
  - conan test ../test_package/conanfile.py JSONSettings/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o boost=%BOOST% -o gtest=%GTEST%
  - cd ..
  - cd test
  - cd JSONSettingsTestUtilities
  - md build
  - cd build
  - conan install .. -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -e VERSION="%APPVEYOR_BUILD_VERSION%" -o boost=%BOOST% -o gtest=%GTEST%
  - cmake .. -G "%VISUAL_STUDIO%"
  - msbuild JSONSettingsTestUtilities.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - conan export-pkg ../conanfile.py JSONSettingsTestUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o boost=%BOOST% -o gtest=%GTEST%
  - conan test ../test_package/conanfile.py JSONSettingsTestUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o boost=%BOOST% -o gtest=%GTEST%
  - cd ..
  - cd ..
  - cd ..
  - cd src
  - cd JSONSettingsRESTAPI
  - md build
  - cd build
  - conan install .. -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -e VERSION="%APPVEYOR_BUILD_VERSION%" -o boost=%BOOST% -o openssl=%OPENSSL% -o gtest=%GTEST%
  - cmake .. -G "%VISUAL_STUDIO%" -A %PLATFORM%
  - msbuild JSONSettingsRESTAPI.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - conan export-pkg ../conanfile.py JSONSettingsRESTAPI/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o boost=%BOOST% -o openssl=%OPENSSL% -o gtest=%GTEST%
  - conan test ../test_package/conanfile.py JSONSettingsRESTAPI/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o boost=%BOOST% -o openssl=%OPENSSL% -o gtest=%GTEST%
  - cd ..
  - cd ..
  - cd ..
  - cd build

test_script:
  - ps: cd bin
  - ps: cd $env:CONFIGURATION
  - JSONSettingsTest.exe --gtest_output=xml:JSONSettingsTest.xml

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\JSONSettingsTest.xml))

artifacts:
  - path: 'build\lib\%CONFIGURATION%\JSONSettings.lib'
    name: JSONSettings.lib
  - path: 'test\JSONSettingsTestUtilities\build\lib\%CONFIGURATION%\JSONSettingsTestUtilities.lib'
    name: JSONSettingsTestUtilities.lib

deploy_script:
  - ps: >- 
      if($env:appveyor_repo_tag -eq 'True') {
        conan upload JSONSettings/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
        conan upload JSONSettingsTestUtilities/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
      } else {
        echo "Not uploading because this is not a tag build"
      }
