#pragma once

#define GET_JSON_SETTING_INT(SERVICE, FILENAMESPACE, SETTINGNAMESPACE) \
	SERVICE.getSettingInteger(FILENAMESPACE::FILEPATH, FILENAMESPACE::SETTINGNAMESPACE::SETTING_PATH, FILENAMESPACE::SETTINGNAMESPACE::DEFAULT)

#define GET_JSON_SETTING_STRING(SERVICE, FILENAMESPACE, SETTINGNAMESPACE) \
	SERVICE.getSettingString(FILENAMESPACE::FILEPATH, FILENAMESPACE::SETTINGNAMESPACE::SETTING_PATH, FILENAMESPACE::SETTINGNAMESPACE::DEFAULT)

#define GET_JSON_SETTING_BOOL(SERVICE, FILENAMESPACE, SETTINGNAMESPACE) \
	(SERVICE.getSettingBoolean(FILENAMESPACE::FILEPATH, FILENAMESPACE::SETTINGNAMESPACE::SETTING_PATH, FILENAMESPACE::SETTINGNAMESPACE::DEFAULT)


#define SET_JSON_SETTING_INT(SERVICE, FILENAMESPACE, SETTINGNAMESPACE, SETTING_VALUE) \
	SERVICE.setSettingInteger(FILENAMESPACE::FILEPATH, FILENAMESPACE::SETTINGNAMESPACE::SETTING_PATH, SETTING_VALUE)

#define SET_JSON_SETTING_STRING(SERVICE, FILENAMESPACE, SETTINGNAMESPACE, SETTING_VALUE) \
	SERVICE.setSettingString(FILENAMESPACE::FILEPATH, FILENAMESPACE::SETTINGNAMESPACE::SETTING_PATH, SETTING_VALUE)

#define SET_JSON_SETTING_BOOL(SERVICE, FILENAMESPACE, SETTINGNAMESPACE, SETTING_VALUE) \
	SERVICE.setSettingBoolean(FILENAMESPACE::FILEPATH, FILENAMESPACE::SETTINGNAMESPACE::SETTING_PATH, SETTING_VALUE)

